### ISSUE TITLE
invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)

### ISSUE THREAD

**Issue by Jeon316upzx** [OpenZeppelin/workshops#18]
AUTOTASK START
2022-06-28T18:19:22.679Z	INFO	Relaying {
  value: 0,
  gas: 1000000,
  nonce: '1',
  to: '0x02f50082297c86E8c4D878D4c7dc68B236D3616c',
  from: '0x84E5B4cf1B91EC15dD34E097B403B07175f72d35',
  data: '0xf2c298be000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000044d617a6900000000000000000000000000000000000000000000000000000000'
}
2022-06-28T18:19:26.459Z	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"invalid BigNumber value (argument=\"value\", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)","code":"INVALID_ARGUMENT","reason":"invalid BigNumber value","argument":"value","stack":["Error: invalid BigNumber value (argument=\"value\", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)","    at Logger.makeError (/opt/nodejs/node_modules/@ethersproject/logger/lib/index.js:233:21)","    at Logger.throwError (/opt/nodejs/node_modules/@ethersproject/logger/lib/index.js:242:20)","    at Logger.throwArgumentError (/opt/nodejs/node_modules/@ethersproject/logger/lib/index.js:245:21)","    at Function.BigNumber.from (/opt/nodejs/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)","    at DefenderRelaySigner.sendTransaction (/opt/nodejs/node_modules/defender-relay-client/lib/ethers/signer.js:88:45)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}
END RequestId: 01339f85-07b3-49f6-b445-74040d7a48c3
AUTOTASK COMPLETE

**Comment by shanfeng9001** [comment]
me too,big shots ,pls guide me

**Comment by shanfeng9001** [comment]
how to decode the result returned by the forwarder.execute() in ethers.js
