### ISSUE TITLE
Import not found

### ISSUE THREAD

**Issue by rad-p** [OpenZeppelin/workshops#4]
```
$ uname -a
Linux 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux



$ npm run test
> workshop-clone@1.0.0 test open-zeppeling/workshops/02-contracts-clone
> hardhat test

Error HH404: File argent-contracts/contracts/modules/VersionManager.sol, imported from contracts/3-argent/import_0.6.sol, not found.

For more info go to https://hardhat.org/HH404 or run Hardhat with --show-stack-traces
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workshop-clone@1.0.0 test: `hardhat test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the workshop-clone@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     2021-03-16T12_50_13_704Z-debug.log


$ cat 021-03-16T12_50_13_704Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'v14.16.0/bin/node',
1 verbose cli   'v14.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle workshop-clone@1.0.0~pretest: workshop-clone@1.0.0
6 info lifecycle workshop-clone@1.0.0~test: workshop-clone@1.0.0
7 verbose lifecycle workshop-clone@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle workshop-clone@1.0.0~test: PATH: .nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:open-zeppeling/workshops/02-contracts-clone/node_modules/.bin:.nvm/versions/node/v14.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle workshop-clone@1.0.0~test: CWD: open-zeppeling/workshops/02-contracts-clone
10 silly lifecycle workshop-clone@1.0.0~test: Args: [ '-c', 'hardhat test' ]
11 silly lifecycle workshop-clone@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle workshop-clone@1.0.0~test: Failed to exec test script
13 verbose stack Error: workshop-clone@1.0.0 test: `hardhat test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid workshop-clone@1.0.0
15 verbose cwd open-zeppeling/workshops/02-contracts-clone
16 verbose Linux 5.8.0-44-generic
17 verbose argv ".nvm/versions/node/v14.16.0/bin/node" ".nvm/versions/node/v14.16.0/bin/npm" "run" "test"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error workshop-clone@1.0.0 test: `hardhat test`
22 error Exit status 1
23 error Failed at the workshop-clone@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by abcoathup** [comment]
Hi @rad-p!  

I am sorry that you had this issue.

We have been able to reproduce this issue by changing to node 14.

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.  In the meantime, you can try the following workaround: change to node 10/12
